# Generated by Django 2.0 on 2019-01-01 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorReader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.CharField(max_length=2, verbose_name='霸王票排行')),
                ('reader', models.IntegerField(verbose_name='读者名')),
                ('reader_name', models.CharField(max_length=25, verbose_name='读者名')),
                ('reader_score', models.IntegerField(verbose_name='分数')),
                ('reader_level', models.CharField(max_length=5, verbose_name='读者等级')),
            ],
            options={
                'verbose_name': '读者霸王票',
                'verbose_name_plural': '读者霸王票',
            },
        ),
        migrations.CreateModel(
            name='FriendChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_chain', models.IntegerField(blank=True, null=True, verbose_name='友链作者id')),
            ],
            options={
                'verbose_name': '作者友链',
                'verbose_name_plural': '作者友链',
            },
        ),
        migrations.CreateModel(
            name='NovelAuthor',
            fields=[
                ('url', models.URLField()),
                ('author_id', models.IntegerField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(help_text='作者名', max_length=25, verbose_name='作者名')),
                ('column_name', models.CharField(help_text='专栏名', max_length=25, verbose_name='专栏名')),
                ('specil_column', models.BooleanField(default=False, help_text='是否驻站', verbose_name='是否驻站')),
                ('column_confession', models.TextField(help_text='作者自白', max_length=500, verbose_name='作者自白')),
                ('collected_num', models.IntegerField(default=0, verbose_name='被收藏数')),
                ('author_notice', models.TextField(max_length=500, verbose_name='主人告示')),
                ('author_weibo', models.URLField(verbose_name='作者微博')),
                ('send_gift', models.IntegerField(default=0, verbose_name='发出红包')),
                ('good_novel', models.TextField(max_length=50)),
                ('last_novel_id', models.IntegerField(default=0, verbose_name='最新作品id')),
                ('last_update_novel', models.CharField(max_length=25, verbose_name='最新作品名')),
                ('last_novel_status', models.CharField(choices=[('1', '已完成'), ('2', '连载中'), ('3', '已暂停')], max_length=1, verbose_name='最新作品状态')),
                ('last_novel_word_count', models.IntegerField(default=0, verbose_name='最新作品字数')),
                ('last_update_time', models.DateTimeField(blank=True, null=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '作者信息',
                'verbose_name_plural': '作者信息',
            },
        ),
        migrations.AddField(
            model_name='friendchain',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_chain', to='authors.NovelAuthor', verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='authorreader',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reader_rank', to='authors.NovelAuthor', verbose_name='作者'),
        ),
    ]
