# Generated by Django 2.0 on 2019-01-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelauthor',
            name='last_novel_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='最新作品id'),
        ),
        migrations.AlterField(
            model_name='novelauthor',
            name='last_novel_status',
            field=models.CharField(blank=True, choices=[('1', '已完成'), ('2', '连载中'), ('3', '已暂停')], max_length=1, null=True, verbose_name='最新作品状态'),
        ),
        migrations.AlterField(
            model_name='novelauthor',
            name='last_novel_word_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='最新作品字数'),
        ),
        migrations.AlterField(
            model_name='novelauthor',
            name='last_update_novel',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='最新作品名'),
        ),
    ]
