# Generated by Django 2.0 on 2019-01-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_auto_20190101_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelauthor',
            name='last_update_novel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='最新作品名'),
        ),
    ]
