# Generated by Django 2.0 on 2019-01-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_auto_20190101_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorreader',
            name='reader_id',
            field=models.IntegerField(null=True, verbose_name='读者id'),
        ),
    ]
