# Generated by Django 2.0 on 2019-01-01 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_authorreader_reader_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorreader',
            name='reader',
        ),
    ]
