# Generated by Django 2.0 on 2019-01-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_remove_authorreader_reader'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelauthor',
            name='click_num',
            field=models.IntegerField(default=0, verbose_name='点击数'),
        ),
    ]
