# Generated by Django 2.0 on 2019-01-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0006_novelauthor_click_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorreader',
            options={'ordering': ['id'], 'verbose_name': '读者霸王票', 'verbose_name_plural': '读者霸王票'},
        ),
        migrations.AlterModelOptions(
            name='novelauthor',
            options={'ordering': ['author_id'], 'verbose_name': '作者信息', 'verbose_name_plural': '作者信息'},
        ),
        migrations.AlterField(
            model_name='novelauthor',
            name='click_num',
            field=models.IntegerField(default=0, help_text='点击数', verbose_name='点击数'),
        ),
    ]
