# Generated by Django 2.0 on 2019-01-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistic', '0002_auto_20181229_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='read_object',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='阅读对象'),
        ),
    ]
