# Generated by Django 2.0 on 2018-12-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181219_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='邀请码')),
            ],
            options={
                'verbose_name': '邀请码',
                'verbose_name_plural': '邀请码',
            },
        ),
    ]
