# Generated by Django 2.0 on 2018-12-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_invitationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='usericon',
            field=models.ImageField(blank=True, default='image/default.png', null=True, upload_to='image/%Y/%m', verbose_name='头像'),
        ),
    ]
