# Generated by Django 2.0 on 2019-01-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_auto_20190102_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='novel_progress',
            field=models.IntegerField(choices=[(1, '已完成'), (2, '连载中'), (3, '暂停')], verbose_name='作品状态'),
        ),
    ]
